[package]
name = "drand-client-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = { version = "0.4.3", features = ["serde"] }
sha2 = "0.9"
bls12_381 = { version = "0.8.0", features = ["experimental"] }
thiserror = "1.0.38"
serde = { version = "1.0.187", features = ["derive"] }
serde_json = "1.0.105"
reqwest = { version = "0.11.20", features = ["blocking", "json"] }